# Generated by Django 3.2.4 on 2021-06-05 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='type',
        ),
    ]
